# Generated by Django 3.2.9 on 2022-01-04 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aparato',
            fields=[
                ('id_aparato', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40, verbose_name='Nombre del aparato')),
            ],
        ),
    ]
