# Generated by Django 3.2.9 on 2022-01-04 21:17

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('seccion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id_tarea', models.BigAutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=70, verbose_name='descripción de la tarea')),
                ('numero', models.PositiveIntegerField(null=True, verbose_name='número de la tarea según imágen')),
                ('seccion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subtarea_tarea', to='seccion.seccion')),
            ],
        ),
        migrations.CreateModel(
            name='SubTarea',
            fields=[
                ('id_subtarea', models.BigAutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=70, verbose_name='Material o tarea')),
                ('costo', models.PositiveIntegerField(verbose_name='Costo')),
                ('repeticiones', models.DecimalField(decimal_places=2, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('Tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pieza.tarea')),
            ],
        ),
    ]
