# Generated by Django 3.2.9 on 2022-01-09 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pieza', '0002_filacarrito'),
    ]

    operations = [
        migrations.DeleteModel(
            name='filaCarrito',
        ),
    ]
