# Generated by Django 3.2.9 on 2022-01-09 17:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pieza', '0003_delete_filacarrito'),
    ]

    operations = [
        migrations.CreateModel(
            name='filaCarrito',
            fields=[
                ('id_fila', models.BigAutoField(primary_key=True, serialize=False)),
                ('costoTarea', models.PositiveIntegerField(verbose_name='Costo Tarea')),
                ('Tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pieza.tarea')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
