# Generated by Django 3.2.9 on 2022-01-16 22:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pieza', '0004_filacarrito'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtarea',
            name='repeticiones',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
    ]
