# Generated by Django 3.2.9 on 2022-01-25 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pieza', '0013_alter_subtarea_repeticiones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filacarrito',
            name='Tarea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filaCarrito_tarea', to='pieza.tarea'),
        ),
    ]
