# Generated by Django 3.2.9 on 2022-01-19 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_alter_user_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='id_admin',
            field=models.BooleanField(default=False),
        ),
    ]
