# Generated by Django 3.2.9 on 2022-01-19 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_user_id_admin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='id_admin',
            new_name='is_admin',
        ),
    ]
