# Generated by Django 3.2.9 on 2022-01-04 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aparato', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seccion',
            fields=[
                ('id_seccion', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40, verbose_name='Nombre de la sección')),
                ('aparato', models.ManyToManyField(to='aparato.Aparato')),
            ],
        ),
    ]
